export enum RarityTypes {
  COMMON = 'COMMON',
  RARE = 'RARE',
  EPIC = 'EPIC',
  LEGENDARY = 'LEGENDARY',
  UNKNOWN = 'UNKNOWN'
}

export const rarityHashMap = {
  'Pink': RarityTypes.COMMON,
  'Citrus': RarityTypes.COMMON,
  'Sky': RarityTypes.COMMON,
  'Silver': RarityTypes.COMMON,
  'Cobalt':RarityTypes.COMMON,
  'Rose Quartz': RarityTypes.COMMON,
  'Nuclear': RarityTypes.COMMON,
  '!Oh': RarityTypes.COMMON,
  'Crying': RarityTypes.COMMON,
  'Zen': RarityTypes.COMMON,
  'Grateful': RarityTypes.COMMON,
  'Receiver': RarityTypes.COMMON,
  'Sprout': RarityTypes.COMMON,
  'Antennae': RarityTypes.COMMON,
  'Hanabi': RarityTypes.COMMON,
  'None': RarityTypes.COMMON,
  'none': RarityTypes.EPIC,
  'Scuffed': RarityTypes.RARE,
  'Abused': RarityTypes.COMMON,
  'Ocean': RarityTypes.RARE,
  'Fruit': RarityTypes.RARE,
  'Midnight': RarityTypes.RARE,
  'Copper': RarityTypes.RARE,
  'Gold': RarityTypes.RARE,
  'Rusty': RarityTypes.RARE,
  'Amethyst': RarityTypes.RARE,
  'Short Circuit': RarityTypes.RARE,
  'Winky': RarityTypes.RARE,
  'StarStruck': RarityTypes.RARE,
  'Grills': RarityTypes.RARE,
  'Plasma': RarityTypes.RARE,
  'Daisy': RarityTypes.RARE,
  'Pristine': RarityTypes.EPIC,
  'Energy Sword': RarityTypes.RARE,
  'Graph': RarityTypes.EPIC,
  'Future': RarityTypes.EPIC,
  'Z Waves': RarityTypes.EPIC,
  'Infrared': RarityTypes.EPIC,
  'Diamond': RarityTypes.EPIC,
  'Graphite': RarityTypes.EPIC,
  'Rainbow': RarityTypes.EPIC,
  'Terminator': RarityTypes.EPIC,
  'Gum': RarityTypes.EPIC,
  'Bot': RarityTypes.EPIC,
  'Fried Egg': RarityTypes.EPIC,
  'The Nest': RarityTypes.EPIC,
  'Cool Chameleon': RarityTypes.EPIC,
  'Sol Sword': RarityTypes.EPIC,
  'Flame Chameleon': RarityTypes.EPIC,
  'Matte': RarityTypes.LEGENDARY,
  'Black on Black': RarityTypes.LEGENDARY,
  'Future Wave': RarityTypes.LEGENDARY,
  'Crystal Blue': RarityTypes.LEGENDARY,
  'Crystal Red': RarityTypes.LEGENDARY,
  'Crystal Yellow': RarityTypes.LEGENDARY,
  'Crystal White': RarityTypes.LEGENDARY,
  'Screentime': RarityTypes.LEGENDARY,
  'Mecha Mask': RarityTypes.LEGENDARY,
  'Double Cool Chameleon': RarityTypes.LEGENDARY,
  'Giga Stabbed': RarityTypes.LEGENDARY,
  'Double Flame Chameleon': RarityTypes.LEGENDARY,
  'Solana': RarityTypes.UNKNOWN,
  'Milky Way': RarityTypes.UNKNOWN,
  'Rover': RarityTypes.UNKNOWN,
  'The Claw': RarityTypes.UNKNOWN,
  'Cute': RarityTypes.UNKNOWN,
  'Immaculate': RarityTypes.UNKNOWN,
  'Perfectly Crisped Toast': RarityTypes.UNKNOWN,
  'Calm Water': RarityTypes.UNKNOWN,
  'Zen Garden': RarityTypes.UNKNOWN,
  'Spooky': RarityTypes.UNKNOWN,
  'Zombie': RarityTypes.UNKNOWN,
  'Giga Plasma': RarityTypes.UNKNOWN,
  'A Lot': RarityTypes.UNKNOWN,
  'Normal': RarityTypes.UNKNOWN,
  'Puzzled': RarityTypes.UNKNOWN,
  'Graph Paper': RarityTypes.UNKNOWN,
  'Jungle': RarityTypes.UNKNOWN,
  'Concrete Jungle': RarityTypes.UNKNOWN,
  'Garden': RarityTypes.UNKNOWN,
  'Cracked': RarityTypes.UNKNOWN,


}

export const attributesArray = {
  background: ['Pink', 'Citrus', 'Sky', 'Ocean', 'Fruit', 'Midnight', 'Graph', 'Future', 'Z Waves', 'Infrared', 'Matte', 'Black on Black'],
  body: ['Silver', 'Cobalt', 'Rose Quartz', 'Nuclear', 'Copper', 'Gold', 'Rusty', 'Amethyst', 'Diamond', 'Graphite', 'Rainbow', 'Crystal Blue', 'Crystal Red', 'Crystal Yellow', 'Crystal White'],
  expression: ['!Oh','Crying', 'Zen', 'Grateful', 'Short Circuit', 'Winky', 'Star Stuck', 'Grills', 'Terminator', 'Gum', 'Bot', 'Screentime', 'Mecha Mask'],
  equipment: ['Receiver', 'Sprout', 'Antennae', 'Hanabi', 'None', 'Plasma', 'Daisy', 'Energy Sword', 'Fried Egg', 'The Nest', 'Cool Chameleon', 'Flame Chameleon', 'Double Cool Chameleon', 'Double Flame Chameleon', 'Sol Sword'],
  damage: ['Pristine', 'Scuffed', 'Abused', 'None']
}
