export const rarityHashMap = {
  'Pink': 'COMMON',
  'Citrus': 'COMMON',
  'Sky': 'COMMON',
  'Silver': 'COMMON',
  'Cobalt':'COMMON',
  'Rose Quartz': 'COMMON',
  'Nuclear': 'COMMON',
  '!Oh': 'COMMON',
  'Crying': 'COMMON',
  'Zen': 'COMMON',
  'Grateful': 'COMMON',
  'Receiver': 'COMMON',
  'Sprout': 'COMMON',
  'Antennae': 'COMMON',
  'Hanabi': 'COMMON',
  'None': 'COMMON',
  'Ocean': 'RARE',
  'Fruit': 'RARE',
  'Midnight': 'RARE',
  'Copper': 'RARE',
  'Gold': 'RARE',
  'Rusty': 'RARE',
  'Amethyst': 'RARE',
  'Short Circuit': 'RARE',
  'Winky': 'RARE',
  'StarStruck': 'RARE',
  'Grills': 'RARE',
  'Plasma': 'RARE',
  'Daisy': 'RARE',
  'Pristine': 'RARE',
  'Energy Sword': 'RARE',
  'Graph': 'PRETTY EPIC',
  'Future': 'PRETTY EPIC',
  'Z Waves': 'PRETTY EPIC',
  'Infrared': 'PRETTY EPIC',
  'Diamond': 'PRETTY EPIC',
  'Graphite': 'PRETTY EPIC',
  'Rainbow': 'PRETTY EPIC',
  'Terminator': 'PRETTY EPIC',
  'Gum': 'PRETTY EPIC',
  'Bot': 'PRETTY EPIC',
  'Fried Egg': 'PRETTY EPIC',
  'The Nest': 'PRETTY EPIC',
  'Cool Chameleon': 'PRETTY EPIC',
  'Sol Sword': 'PRETTY EPIC',
  'Flame Chameleon': 'PRETTY EPIC',
  'Matte': 'DANG, LEGENDARY',
  'Black on Black': 'DANG, LEGENDARY',
  'Crystal Blue': 'DANG, LEGENDARY',
  'Crystal Red': 'DANG, LEGENDARY',
  'Crystal Yellow': 'DANG, LEGENDARY',
  'Crystal White': 'DANG, LEGENDARY',
  'Screentime': 'DANG, LEGENDARY',
  'Mecha Mask': 'DANG, LEGENDARY',
  'Double Cool Chameleon': 'DANG, LEGENDARY',
  'Giga Stabbed': 'DANG, LEGENDARY',
  'Double Flame Chameleon': 'DANG, LEGENDARY',
  'Scuffed': 'COMMON',
  'Abused': 'COMMON',
}

export const attributesArray = {
  background: ['Pink', 'Citrus', 'Sky', 'Ocean', 'Fruit', 'Midnight', 'Graph', 'Future', 'Z Waves', 'Infrared', 'Matte', 'Black on Black'],
  body: ['Silver', 'Cobalt', 'Rose Quartz', 'Nuclear', 'Copper', 'Gold', 'Rusty', 'Amethyst', 'Diamond', 'Graphite', 'Rainbow', 'Crystal Blue', 'Crystal Red', 'Crystal Yellow', 'Crystal White'],
  expression: ['!Oh','Crying', 'Zen', 'Grateful', 'Short Circuit', 'Winky', 'Star Stuck', 'Grills', 'Terminator', 'Gum', 'Bot', 'Screentime', 'Mecha Mask'],
  equipment: ['Receiver', 'Sprout', 'Antennae', 'Hanabi', 'None', 'Plasma', 'Daisy', 'Energy Sword', 'Fried Egg', 'The Nest', 'Cool Chameleon', 'Flame Chameleon', 'Double Cool Chameleon', 'Double Flame Chameleon', 'Sol Sword'],
  damage: ['Pristine', 'Scuffed', 'Abused', 'None']
}
